--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigsmileXD/libstructure
projects:
  libstructure:
    path: ""
    model: virion
    type: library
    libs:
      - src: thebigsmilexd/libblockstate/libblockstate
        version: ^0.0.0
        branch: master
...
